import fs from 'fs';
import path from 'path';
import { getSetting } from './db.js';

// Writes AssettoServer's extra_cfg.yml into <dataDir>/serverfiles/cfg/.
// server_cfg.ini / entry_list.ini stay with writeAcConfigs — AssettoServer
// reads the same INI files; extra_cfg.yml carries the extras.
// Hand-rolled YAML — no deps, keys match ACExtraConfiguration.

function ystr(v) {
  return `"${String(v ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
function ybool(v) {
  return v ? 'true' : 'false';
}
function ylist(arr) {
  if (!Array.isArray(arr) || !arr.length) return '[]';
  return `\n${arr.map((x) => `  - ${ystr(x)}`).join('\n')}`;
}

export async function writeAssettoServerExtraCfg(dataDir, config, { telemetryEnabled = true } = {}) {
  const cfgDir = path.join(dataDir, 'serverfiles', 'cfg');
  fs.mkdirSync(cfgDir, { recursive: true });
  fs.mkdirSync(path.join(cfgDir, 'cm_content'), { recursive: true });

  const e = config.extra || {};
  let description = e.serverDescription || '';
  if (!description) {
    const baseUrl = String(await getSetting('public_base_url', '')).replace(/\/+$/, '');
    if (baseUrl) description = `Server info & downloads: ${baseUrl}`;
  }

  const lines = ['# Generated by AssettoMan — edit via the server config page'];
  if (e.minimumCspVersion) lines.push(`MinimumCSPVersion: ${e.minimumCspVersion}`);
  lines.push(`UseSteamAuth: ${ybool(e.useSteamAuth)}`);
  lines.push('EnableServerDetails: true'); // required so CM can fetch cm_content/content.json
  lines.push(`ServerDescription: ${ystr(description)}`);
  lines.push(`EnableAi: ${ybool(e.enableAi)}`);
  lines.push(`EnableWeatherFx: ${ybool(e.enableWeatherFx)}`);
  lines.push(`EnableRealTime: ${ybool(e.enableRealTime)}`);
  lines.push(`EnableCarReset: ${ybool(e.enableCarReset)}`);
  lines.push(`EnableSessionVote: ${ybool(e.enableSessionVote)}`);
  lines.push(`EnableKickPlayerVote: ${ybool(e.enableKickPlayerVote)}`);
  lines.push(`VoteKickMinimumConnectedPlayers: ${e.voteKickMinimumConnectedPlayers ?? 3}`);
  lines.push(`ForceLights: ${ybool(e.forceLights)}`);
  lines.push(`EnableGlobalDrs: ${ybool(e.enableGlobalDrs)}`);
  lines.push(`EnableUnlimitedP2P: ${ybool(e.enableUnlimitedP2P)}`);
  lines.push(`EnableLegacyPluginInterface: ${ybool(telemetryEnabled)}`);
  lines.push('EnableUPnP: false');
  lines.push(`LoadingImageUrls: ${ylist(e.loadingImageUrls)}`);
  lines.push(`EnablePlugins: ${ylist(e.enablePlugins)}`);
  lines.push('');

  fs.writeFileSync(path.join(cfgDir, 'extra_cfg.yml'), lines.join('\n'), 'utf8');
}
