// Static game data used by config UIs and writers.

export const ACC_TRACKS = [
  { id: 'barcelona', label: 'Circuit de Barcelona-Catalunya', dlc: 'base' },
  { id: 'brands_hatch', label: 'Brands Hatch', dlc: 'base' },
  { id: 'hungaroring', label: 'Hungaroring', dlc: 'base' },
  { id: 'misano', label: 'Misano World Circuit', dlc: 'base' },
  { id: 'monza', label: 'Monza', dlc: 'base' },
  { id: 'nurburgring', label: 'Nürburgring GP', dlc: 'base' },
  { id: 'paul_ricard', label: 'Paul Ricard', dlc: 'base' },
  { id: 'silverstone', label: 'Silverstone', dlc: 'base' },
  { id: 'spa', label: 'Spa-Francorchamps', dlc: 'base' },
  { id: 'zandvoort', label: 'Zandvoort', dlc: 'base' },
  { id: 'zolder', label: 'Zolder', dlc: 'base' },
  { id: 'imola', label: 'Imola', dlc: '2020 GTWC' },
  { id: 'kyalami', label: 'Kyalami', dlc: 'IGTC' },
  { id: 'laguna_seca', label: 'Laguna Seca', dlc: 'IGTC' },
  { id: 'mount_panorama', label: 'Mount Panorama (Bathurst)', dlc: 'IGTC' },
  { id: 'suzuka', label: 'Suzuka', dlc: 'IGTC' },
  { id: 'indianapolis', label: 'Indianapolis', dlc: 'IGTC' },
  { id: 'donington', label: 'Donington Park', dlc: 'British GT' },
  { id: 'oulton_park', label: 'Oulton Park', dlc: 'British GT' },
  { id: 'snetterton', label: 'Snetterton', dlc: 'British GT' },
  { id: 'cota', label: 'Circuit of the Americas', dlc: 'American Track' },
  { id: 'watkins_glen', label: 'Watkins Glen', dlc: 'American Track' },
  { id: 'valencia', label: 'Valencia (Ricardo Tormo)', dlc: '2023 GTWC' },
  { id: 'nurburgring_24h', label: 'Nürburgring 24h', dlc: 'N24' },
];

// ACC car model IDs (forcedCarModel / BoP entries). Includes DLC cars.
export const ACC_CARS = [
  { id: 0, label: 'Porsche 911 GT3 R (991)', group: 'GT3' },
  { id: 1, label: 'Mercedes-AMG GT3 (2015)', group: 'GT3' },
  { id: 2, label: 'Ferrari 488 GT3', group: 'GT3' },
  { id: 3, label: 'Audi R8 LMS (2015)', group: 'GT3' },
  { id: 4, label: 'Lamborghini Huracán GT3 (2015)', group: 'GT3' },
  { id: 5, label: 'McLaren 650S GT3', group: 'GT3' },
  { id: 6, label: 'Nissan GT-R Nismo GT3 (2018)', group: 'GT3' },
  { id: 7, label: 'BMW M6 GT3', group: 'GT3' },
  { id: 8, label: 'Bentley Continental GT3 (2018)', group: 'GT3' },
  { id: 9, label: 'Porsche 911 GT3 Cup (991 II)', group: 'GTC' },
  { id: 10, label: 'Nissan GT-R Nismo GT3 (2015)', group: 'GT3' },
  { id: 11, label: 'Bentley Continental GT3 (2015)', group: 'GT3' },
  { id: 12, label: 'Aston Martin V12 Vantage GT3', group: 'GT3' },
  { id: 13, label: 'Lamborghini Gallardo R-EX', group: 'GT3' },
  { id: 14, label: 'Jaguar G3 (Emil Frey)', group: 'GT3' },
  { id: 15, label: 'Lexus RC F GT3', group: 'GT3' },
  { id: 16, label: 'Lamborghini Huracán GT3 Evo', group: 'GT3' },
  { id: 17, label: 'Honda NSX GT3 (2017)', group: 'GT3' },
  { id: 18, label: 'Audi R8 LMS Evo (2019)', group: 'GT3' },
  { id: 19, label: 'Aston Martin V8 Vantage AMR GT3 (2019)', group: 'GT3' },
  { id: 20, label: 'Honda NSX GT3 Evo (2019)', group: 'GT3' },
  { id: 21, label: 'McLaren 720S GT3', group: 'GT3' },
  { id: 22, label: 'Porsche 911 II GT3 R (2019)', group: 'GT3' },
  { id: 23, label: 'Porsche 718 Cayman GT4 MR', group: 'GT4' },
  { id: 24, label: 'Aston Martin Vantage AMR GT4', group: 'GT4' },
  { id: 25, label: 'Audi R8 LMS GT4', group: 'GT4' },
  { id: 26, label: 'BMW M4 GT4', group: 'GT4' },
  { id: 27, label: 'Chevrolet Camaro GT4.R', group: 'GT4' },
  { id: 28, label: 'Ginetta G55 GT4', group: 'GT4' },
  { id: 29, label: 'KTM X-Bow GT4', group: 'GT4' },
  { id: 30, label: 'Maserati GranTurismo MC GT4', group: 'GT4' },
  { id: 31, label: 'McLaren 570S GT4', group: 'GT4' },
  { id: 32, label: 'Mercedes-AMG GT4', group: 'GT4' },
  { id: 33, label: 'Lamborghini Huracán Super Trofeo', group: 'GTC' },
  { id: 34, label: 'Ferrari 488 GT3 Evo (2020)', group: 'GT3' },
  { id: 35, label: 'Mercedes-AMG GT3 Evo (2020)', group: 'GT3' },
  { id: 36, label: 'BMW M4 GT3 (2022)', group: 'GT3' },
  { id: 50, label: 'BMW M2 CS Racing', group: 'TCX' },
  { id: 51, label: 'Alpine A110 GT4', group: 'GT4' },
  { id: 52, label: 'Audi R8 LMS GT2', group: 'GT2' },
  { id: 53, label: 'KTM X-Bow GT2', group: 'GT2' },
  { id: 55, label: 'Maserati MC20 GT2', group: 'GT2' },
  { id: 56, label: 'Mercedes-AMG GT2', group: 'GT2' },
  { id: 57, label: 'Porsche 911 GT2 RS CS', group: 'GT2' },
  { id: 58, label: 'Porsche 935 (2019)', group: 'GT2' },
  { id: 59, label: 'Brabham BT63 GT2', group: 'GT2' },
  { id: 60, label: 'Lamborghini Huracán Super Trofeo EVO2', group: 'GTC' },
  { id: 61, label: 'Ferrari 488 Challenge Evo', group: 'GTC' },
];

export const ACC_CAR_GROUPS = ['FreeForAll', 'GT3', 'GT4', 'GTC', 'TCX', 'GT2'];

export const ACC_SESSION_TYPES = ['P', 'Q', 'R']; // Practice / Qualifying / Race

export const ACC_DRIVER_CATEGORIES = ['Bronze', 'Silver', 'Gold', 'Platinum'];

export const IMAGES = {
  ac: 'ghcr.io/ich777/steamcmd:assettocorsa',
  ac_modded: 'ghcr.io/ich777/steamcmd:assettocorsa',
  assettoserver: 'compujuckel/assettoserver:latest',
  acc: 'ghcr.io/ich777/accompetizione-server',
};

export const DEFAULT_PORTS = {
  ac: { game: 9600, http: 8081, plugin: 9700, pluginListen: 9701 },
  ac_modded: { game: 9610, http: 8091, plugin: 9710, pluginListen: 9711 },
  assettoserver: { game: 9620, http: 8101, plugin: 9720, pluginListen: 9721 },
  acc: { game: 9201 },
};

// Default AC server_cfg.ini fields (SERVER section + sessions).
export function defaultAcConfig() {
  return {
    server: {
      name: 'AssettoMan Server',
      cars: 'ks_abarth500_assetto_corse',
      track: 'magione',
      trackConfig: '',
      sunAngle: 16,
      maxClients: 12,
      raceOverTime: 120,
      allowedTyresOut: -1,
      password: '',
      adminPassword: 'changeMeAdmin',
      loopMode: 1,
      registerToLobby: 1,
      pickupModeEnabled: 1,
      sleepTime: 1,
      clientSendIntervalHz: 18,
      sendBufferSize: 0,
      recvBufferSize: 0,
      kickAfkTime: 0,
      qualifyMaxWaitPerc: 400,
      tyreWearFactor: 1,
      fuelConsumptionRate: 1,
      damageMultiplier: 100,
      votingQuorum: 75,
      voteDuration: 20,
      blacklistMode: 0,
      tcAllowed: 1,
      absAllowed: 1,
      stabilityAllowed: 0,
      autoClutchAllowed: 1,
      forceVirtualMirror: 0,
      legalTyres: '',
      maxBallastKg: 50,
      udpPluginLocalPort: 0,
      udpPluginAddress: '',
      authPluginAddress: '',
      startRule: 0,
      raceGasPenaltyDisabled: 0,
      timeOfDayMult: 1,
      resultScreenTime: 0,
      lockEntryList: 0,
      racePitWindowStart: 0,
      racePitWindowEnd: 0,
      reversedGridRacePositions: 0,
      numThreads: 2,
    },
    practice: { enabled: true, name: 'Free Practice', timeMinutes: 20, isOpen: 1 },
    qualify: { enabled: true, name: 'Qualifying', timeMinutes: 15, isOpen: 1 },
    race: { laps: 10, timeMinutes: 0, waitTime: 60, name: 'Race' },
    dynamicTrack: { sessionStart: 95, randomness: 2, sessionTransfer: 90, lapGain: 10 },
    weathers: [
      { graphics: '3_clear', baseTempAmbient: 22, baseTempRoad: 4, variationAmbient: 1, variationRoad: 1, windBaseSpeedMin: 3, windBaseSpeedMax: 15, windBaseDirection: 0, windVariationDirection: 15 },
    ],
    entries: [],
    booked: [],
    telemetry: { enabled: true, forwardTo: '' },
    // AssettoServer extra_cfg.yml fields (only used by type === 'assettoserver')
    extra: {
      minimumCspVersion: 2000,
      useSteamAuth: false,
      serverDescription: '',
      enableAi: false,
      enableWeatherFx: true,
      enableRealTime: false,
      enableCarReset: false,
      enableSessionVote: true,
      enableKickPlayerVote: true,
      voteKickMinimumConnectedPlayers: 3,
      forceLights: false,
      enableGlobalDrs: true,
      enableUnlimitedP2P: true,
      loadingImageUrls: [],
      enablePlugins: [],
    },
  };
}

// Default ACC cfg/*.json contents (mirrors stock ACC dedicated server).
export function defaultAccConfig() {
  return {
    configuration: {
      udpPort: 9201,
      tcpPort: 9201,
      maxConnections: 24,
      lanDiscovery: 1,
      registerToLobby: 1,
      configVersion: 1,
    },
    settings: {
      serverName: 'AssettoMan ACC',
      adminPassword: 'adminDocker',
      carGroup: 'FreeForAll',
      trackMedalsRequirement: -1,
      safetyRatingRequirement: -1,
      racecraftRatingRequirement: -1,
      password: '',
      maxCarSlots: 24,
      spectatorPassword: '',
      dumpLeaderboards: 1,
      isRaceLocked: 0,
      randomizeTrackWhenEmpty: 0,
      centralEntryListPath: '',
      allowAutoDQ: 1,
      shortFormationLap: 0,
      dumpEntryList: 0,
      formationLapType: 3,
      ignorePrematureDisconnects: 0,
      configVersion: 1,
    },
    event: {
      track: 'spa',
      preRaceWaitingTimeSeconds: 80,
      sessionOverTimeSeconds: 120,
      ambientTemp: 26,
      cloudLevel: 0.3,
      rain: 0.0,
      weatherRandomness: 1,
      postQualySeconds: 60,
      postRaceSeconds: 90,
      simracerWeatherConditions: 0,
      isFixedConditionQualification: 1,
      sessions: [
        { hourOfDay: 14, dayOfWeekend: 2, timeMultiplier: 1, sessionType: 'P', sessionDurationMinutes: 20 },
        { hourOfDay: 15, dayOfWeekend: 2, timeMultiplier: 1, sessionType: 'Q', sessionDurationMinutes: 15 },
        { hourOfDay: 16, dayOfWeekend: 3, timeMultiplier: 1, sessionType: 'R', sessionDurationMinutes: 45 },
      ],
      configVersion: 1,
    },
    eventRules: {
      qualifyStandingType: 1,
      pitWindowLengthSec: -1,
      driverStintTimeSec: -1,
      mandatoryPitstopCount: 0,
      maxTotalDrivingTime: -1,
      maxDriversCount: 1,
      isRefuellingAllowedInRace: 1,
      isRefuellingTimeFixed: 0,
      isMandatoryPitstopRefuellingRequired: 0,
      isMandatoryPitstopTyreChangeRequired: 0,
      isMandatoryPitstopSwapDriverRequired: 0,
      tyreSetCount: 50,
      configVersion: 1,
    },
    assistRules: {
      stabilityControlLevelMax: 25,
      disableAutosteer: 1,
      disableAutoLights: 0,
      disableAutoWiper: 0,
      disableAutoEngineStart: 0,
      disableAutoPitLimiter: 0,
      disableAutoGear: 0,
      disableAutoClutch: 0,
      disableIdealLine: 0,
      configVersion: 1,
    },
    entrylist: { entries: [], configVersion: 1 },
    bop: { entries: [], configVersion: 1 },
  };
}
